version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pearspective-db
    restart: always
    environment:
      POSTGRES_DB: pearspective
      POSTGRES_USER: sergio
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
