# Arquivo de override para personalizações locais
# Este arquivo é automaticamente carregado pelo docker-compose
# e permite sobrescrever configurações do docker-compose.yml

services:
  # Override da aplicação para desenvolvimento local
  app:
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    volumes:
      # Mapear código fonte para hot reload (desenvolvimento)
      - .:/app
      - /app/node_modules  # Volume para node_modules
    # Comentado por padrão - descomente para desenvolvimento
    # command: npm run dev

  # Override do PostgreSQL para desenvolvimento
  postgres:
    environment:
      - POSTGRES_DB=pearspective
    # Descomente para persistir dados em desenvolvimento
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data

  # Override do Nginx (comentado por padrão)
  # nginx:
  #   ports:
  #     - "8080:80"  # Mudar porta se necessário
  #     - "8443:443" # Mudar porta se necessário

  # Adicionar Redis para desenvolvimento (descomente se necessário)
  # redis:
  #   image: redis:7-alpine
  #   container_name: perspective_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - perspective_network

# volumes:
#   redis_data:
#     driver: local 