services:
  # Frontend (Static Site)
  - type: web
    name: pearspective-frontend
    env: static
    buildCommand: null
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API
  - type: web
    name: pearspective-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node api/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 5432

  # PostgreSQL Database
  - type: pserv
    name: pearspective-db
    env: postgresql
    plan: free
    ipAllowList: [] 